In [19]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

In [20]:
df=pd.DataFrame(data={
    "shape": ["circle","square","triangle","circle","square","triangle","triangle","circle","square","circle"],
    "area" : [28.3, 36.0, 45.0, 78.6, 25.0, 45.4, 74.6, 23.0, 45.6, 40.5],
    "price": [99, 199, 299, 399, 499, 599, 699, 799, 899, 999],
    "target": ["class1","class2","class1","class2","class1","class2","class1","class2","class1","class2"]
})
df

      shape  area  price  target
0    circle  28.3     99  class1
1    square  36.0    199  class2
2  triangle  45.0    299  class1
3    circle  78.6    399  class2
4    square  25.0    499  class1
5  triangle  45.4    599  class2
6  triangle  74.6    699  class1
7    circle  23.0    799  class2
8    square  45.6    899  class1
9    circle  40.5    999  class2

In [21]:
x=df.drop(columns='target')
y= df['target']

In [22]:
xtrain,xtest,ytrain,ytest= train_test_split(x,y,train_size=0.8, random_state=42)

In [23]:
xtrain

      shape  area  price
5  triangle  45.4    599
0    circle  28.3     99
7    circle  23.0    799
2  triangle  45.0    299
9    circle  40.5    999
4    square  25.0    499
3    circle  78.6    399
6  triangle  74.6    699

In [24]:
encoder=LabelEncoder()

In [25]:
# encoder.fit_transform(xtrain)      # ValueError: y should be a 1d array, got an array of shape (8, 3) instead.

In [26]:
encoder.fit_transform(xtrain['shape'])

array([2, 0, 0, 2, 0, 1, 0, 2])

In [27]:
encoder.transform(xtest['shape'])

array([1, 1])

***Scenario-2***

In [28]:
encoder.transform(['triangle'])

array([2])

***Scenario-3***

In [ ]:
encoder.transform(['cone'])          # ValueError: y contains previously unseen labels: 'cone'

ValueError: y contains previously unseen labels: 'cone'