In [74]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OrdinalEncoder

In [75]:
df=pd.DataFrame({
    "Category" : ["Electronics","Clothing","Grocery","Electronics","Clothing","Furniture","Grocery","Electronics","Furniture","Clothing"],
    "Brand" : ["Samsung","Nike","Nestle","Apple","Adidas","IKEA","Amul","Sony","Godrej","Puma"],
    "target": ["class0","class1","class2","class3","class2","class1","class2","class1","class2","class1"]
})
df

      Category    Brand  target
0  Electronics  Samsung  class0
1     Clothing     Nike  class1
2      Grocery   Nestle  class2
3  Electronics    Apple  class3
4     Clothing   Adidas  class2
5    Furniture     IKEA  class1
6      Grocery     Amul  class2
7  Electronics     Sony  class1
8    Furniture   Godrej  class2
9     Clothing     Puma  class1

In [76]:
x=df.drop(columns='target')
y=df['target']

In [77]:
xtrain,xtest,ytain,ytest= train_test_split(x,y,train_size=0.8,random_state=42)

In [78]:
xtrain

      Category    Brand
5    Furniture     IKEA
0  Electronics  Samsung
7  Electronics     Sony
2      Grocery   Nestle
9     Clothing     Puma
4     Clothing   Adidas
3  Electronics    Apple
6      Grocery     Amul

In [79]:
xtrain['Category'].unique()

<StringArray>
['Furniture', 'Electronics', 'Grocery', 'Clothing']
Length: 4, dtype: str

In [80]:
xtrain['Brand'].unique()

<StringArray>
['IKEA', 'Samsung', 'Sony', 'Nestle', 'Puma', 'Adidas', 'Apple', 'Amul']
Length: 8, dtype: str

In [81]:
encoder = OrdinalEncoder(
    categories=[['Furniture','Electronics','Grocery','Clothing'],["IKEA","Samsung","Sony","Nestle","Puma","Adidas","Apple","Amul"]],
    handle_unknown='use_encoded_value',
    unknown_value=-1
)

encoder.fit_transform(xtrain)

array([[0., 0.],
       [1., 1.],
       [1., 2.],
       [2., 3.],
       [3., 4.],
       [3., 5.],
       [1., 6.],
       [2., 7.]])

In [82]:
encoder.transform(xtest)

array([[ 0., -1.],
       [ 3., -1.]])

In [83]:
new_input=[["Salt",'TATA']]

In [84]:
encoder.transform(new_input)

c:\Users\KAPIL SHARMA\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(

array([[-1., -1.]])

In [85]:
new_input=[['Milk','Amul']]

In [86]:
encoder.transform(new_input)

c:\Users\KAPIL SHARMA\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(

array([[-1.,  7.]])

***Scenario-1***

In [87]:
# encoder = OrdinalEncoder(
#     categories=[['Furniture','Electronics','Grocery','Clothing'],["IKEA","Samsung","Sony","Nestle","Puma","Adidas","Apple","Amul"]],
#     handle_unknown='use_encoded_value',
#     unknown_value=-1
# )

# fit=encoder.fit_transform(xtrain[['Category']])
# fit

# '''
# ValueError: Shape mismatch: if categories is an array, it has to be of shape (n_features,).
# '''
# # at time of model training we trained the model using 3 col but here we did not mentioned shape order

***Scenario-2***

In [88]:
encoder = OrdinalEncoder(
    categories=[['Furniture','Electronics','Grocery','Clothing'],["IKEA","Samsung","Sony","Nestle","Puma","Adidas","Apple","Amul"]],
    handle_unknown='use_encoded_value',
    unknown_value=-1
)

encoder.fit_transform(xtrain[['Category','Brand']])

array([[0., 0.],
       [1., 1.],
       [1., 2.],
       [2., 3.],
       [3., 4.],
       [3., 5.],
       [1., 6.],
       [2., 7.]])

In [89]:
encoder = OrdinalEncoder(
    categories=[['Furniture','Electronics','Grocery','Clothing'],["IKEA","Samsung","Sony","Nestle","Puma","Adidas","Apple","Amul"]],
    handle_unknown='use_encoded_value'
)

encoder.fit_transform(xtrain[['Category','Brand']])

TypeError: unknown_value should be an integer or np.nan when handle_unknown is 'use_encoded_value', got None.

In [90]:
encoder = OrdinalEncoder(
    categories=[['Furniture','Electronics','Grocery','Clothing'],["IKEA","Samsung","Sony","Nestle","Puma","Adidas","Apple","Amul"]],
)

encoder.fit_transform(xtrain[['Category','Brand']])

array([[0., 0.],
       [1., 1.],
       [1., 2.],
       [2., 3.],
       [3., 4.],
       [3., 5.],
       [1., 6.],
       [2., 7.]])

In [94]:
encoder = OrdinalEncoder(
    categories=[['Furniture','Electronics','Grocery','Clothing'],["IKEA","Samsung","Sony","Nestle","Puma","Adidas","Apple","Amul"]],
    
)
encoder.fit_transform(xtrain[['Brand','Category']])

'''
ValueError: Found unknown categories ['Adidas', 'Apple', 'IKEA', 'Amul', 'Nestle', 'Sony', 'Samsung', 'Puma'] in column 0 during fit

to handle this we need to pass handle_unknown and unknown_value

unknown_value = -1 is mandatory, should not pass 0 as model will get confused, because it assign 0 to first order and 0 to unknown value alse.
'''

ValueError: Found unknown categories ['Nestle', 'Samsung', 'IKEA', 'Sony', 'Adidas', 'Apple', 'Amul', 'Puma'] in column 0 during fit

In [95]:
encoder = OrdinalEncoder(
    categories=[['Furniture','Electronics','Grocery','Clothing'],["IKEA","Samsung","Sony","Nestle","Puma","Adidas","Apple","Amul"]],
    handle_unknown="use_encoded_value",
    unknown_value= -1
)
encoder.fit_transform(xtrain[['Brand','Category']])

array([[-1., -1.],
       [-1., -1.],
       [-1., -1.],
       [-1., -1.],
       [-1., -1.],
       [-1., -1.],
       [-1., -1.],
       [-1., -1.]])

***Scenario-3***

In [ ]:
# x=pd.DataFrame(data={
#     'Category':['Chayvanprash',"Bed","Diamond","Gold"],
#     "Brand":['Dabar','Honeywell',"Mountblue",'Malawar']
# })
# print(x)
# encoder = OrdinalEncoder(
#     categories=[['Furniture','Electronics','Grocery','Clothing'],["IKEA","Samsung","Sony","Nestle","Puma","Adidas","Apple","Amul"]],
#     handle_unknown='use_encoded_value',
#     unknown_value=-1
# )

# encoder.fit_transform(x[['Category']])


# #                                 '''
# #                                  ValueError: Shape mismatch: if categories is an array, it has to be of shape (n_features,).
# #                                 '''

new_input1=[['A-36','Samsung']]
encoder.transform(new_input1)

# #                                  '''
# #                                   NotFittedError: This OrdinalEncoder instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.
# #                                  '''

       Category      Brand
0  Chayvanprash      Dabar
1           Bed  Honeywell
2       Diamond  Mountblue
3          Gold    Malawar

NotFittedError: This OrdinalEncoder instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.

In [102]:
x=pd.DataFrame(data={
    'Category':['Chayvanprash',"Bed","Diamond","Gold"],
    "Brand":['Dabar','Honeywell',"Mountblue",'Malawar']
})
encoder = OrdinalEncoder(
    categories=[['Furniture','Electronics','Grocery','Clothing'],["IKEA","Samsung","Sony","Nestle","Puma","Adidas","Apple","Amul"]],
    handle_unknown='use_encoded_value',
    unknown_value=-1
)
encoder.fit_transform(x[['Category',"Brand"]])

'''
It will work as it contain all values that are present in column.
'''

new_input2=[['Toothpaste','Himalaya']]
encoder.transform(new_input2)

c:\Users\KAPIL SHARMA\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(

array([[-1., -1.]])