In [180]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OrdinalEncoder

In [181]:
df=pd.DataFrame(
    {
    "color": ["red","blue","green","blue","red","green","green","green","red","blue"],
    "size": ["S","M","L","XL","S","L","S","M","XL","M"],
    "shape": ["circle","square","triangle","circle","square","triangle","triangle","circle","square","circle"],
    "area" : [25, 36, 38, 25.8, 85, 45, 65, 74, 20, 41],
    "target": ["class1","class2","class1","class2","class1","class2","class1","class2","class1","class2"]
    }
)
df

   color size     shape  area  target
0    red    S    circle  25.0  class1
1   blue    M    square  36.0  class2
2  green    L  triangle  38.0  class1
3   blue   XL    circle  25.8  class2
4    red    S    square  85.0  class1
5  green    L  triangle  45.0  class2
6  green    S  triangle  65.0  class1
7  green    M    circle  74.0  class2
8    red   XL    square  20.0  class1
9   blue    M    circle  41.0  class2

In [182]:
x=df.drop(columns='target')
y=df['target']

In [183]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,train_size=0.8,random_state=42)

In [184]:
xtrain

   color size     shape  area
5  green    L  triangle  45.0
0    red    S    circle  25.0
7  green    M    circle  74.0
2  green    L  triangle  38.0
9   blue    M    circle  41.0
4    red    S    square  85.0
3   blue   XL    circle  25.8
6  green    S  triangle  65.0

In [185]:
df['color'].unique()

<StringArray>
['red', 'blue', 'green']
Length: 3, dtype: str

In [186]:
df['size'].unique()

<StringArray>
['S', 'M', 'L', 'XL']
Length: 4, dtype: str

In [187]:
df['shape'].unique()

<StringArray>
['circle', 'square', 'triangle']
Length: 3, dtype: str

In [188]:
encoder= OrdinalEncoder(
    categories=[['red', 'blue', 'green'],['S', 'M', 'L', 'XL'],['circle', 'square', 'triangle']],
    handle_unknown='use_encoded_value',
    unknown_value=-1,
)

encoder.fit_transform(xtrain[['color','size','shape']])         # accept 2D input

array([[2., 2., 2.],
       [0., 0., 0.],
       [2., 1., 0.],
       [2., 2., 2.],
       [1., 1., 0.],
       [0., 0., 1.],
       [1., 3., 0.],
       [2., 0., 2.]])

In [189]:
encoder.fit_transform(xtest[['color','size','shape']])

array([[0., 3., 1.],
       [1., 1., 1.]])

In [190]:
new_input= [['green','XS','circle']]
print(encoder.fit_transform(new_input))
encoder.transform(new_input)

[[ 2. -1.  0.]]

array([[ 2., -1.,  0.]])

In [191]:
new_input=[['Yellow','XXL','circle']]
print(encoder.fit_transform(new_input))
print(encoder.transform(new_input))

[[-1. -1.  0.]]
[[-1. -1.  0.]]

***Scenario-1***

In [192]:
# encoder = OrdinalEncoder(
#     categories=[['red','blue','green'],["S","M","XL","L"]],
#     handle_unknown='use_encoded_value',
#     unknown_value=-1
# )

# # encoder.fit_transform(xtrain[['color','size','shape']])    # ValueError: Shape mismatch: if categories is an array, it has to be of shape (n_features,).

In [193]:
# new_input=[['Yellow','XXL']]

# print(encoder.transform(new_input))

# # ValueError: X has 2 features, but OrdinalEncoder is expecting 3 features as input.

***Scenario-2***

In [194]:
encoder = OrdinalEncoder(
    categories=[['red','blue','green'],["S","M","XL","L"]],
)

# encoder.fit_transform(xtrain[['color','size']])  

# encoder.fit_transform(xtrain[['size', 'color']])  # ValueError: Found unknown categories ['L', 'M', 'XL', 'S'] in column 0 during fit

In [195]:
encoder = OrdinalEncoder(
    categories=[['red','blue','green'],["S","M","XL","L"]],
    handle_unknown='use_encoded_value',
    unknown_value=-1
)

encoder.fit_transform(xtrain[['size', 'color']])

array([[-1., -1.],
       [-1., -1.],
       [-1., -1.],
       [-1., -1.],
       [-1., -1.],
       [-1., -1.],
       [-1., -1.],
       [-1., -1.]])

***Scenario-3***

In [196]:
x=pd.DataFrame(data={
    'color':['red',"blue","blue","red","red","blue"],
    "size":['S','M',"L",'XL','X','L']
})
print(x)
encoder = OrdinalEncoder(
    categories=[['red','blue','green'],["S","M","XL","L"]],
    handle_unknown='use_encoded_value',
    unknown_value=-1
)

#  encoder.fit_transform(x[['color']])

# '''
# ValueError: Shape mismatch: if categories is an array, it has to be of shape (n_features,).
# '''

# new_input1=[['red','S']]
# encoder.transform(new_input1)

# # '''

# # NotFittedError: This OrdinalEncoder instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.
# # '''

  color size
0   red    S
1  blue    M
2  blue    L
3   red   XL
4   red    X
5  blue    L

In [197]:
x=pd.DataFrame(data={
    'color':['red',"blue","blue","red","red","blue"],
    "size":['S','M',"L",'XL','X','L']
})

encoder = OrdinalEncoder(
    categories=[['red','blue','green'],["S","M","XL","L"]],
    handle_unknown='use_encoded_value',
    unknown_value=-1
)

encoder.fit_transform(x[['color','size']])

'''
It will work as it contain all values that are present in column.
'''

new_input2=[['yellow','S']]
encoder.transform(new_input2)

c:\Users\KAPIL SHARMA\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(

array([[-1.,  0.]])