In [71]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split

In [72]:
df=pd.DataFrame(
    {
    "color":["Blue","Red","Red","Blue"],
    "product_type": ["wood","plastic","wood","wood"],
    "label": ["class0","calss1","class2","class0"]
}
)
df

  color product_type   label
0  Blue         wood  class0
1   Red      plastic  calss1
2   Red         wood  class2
3  Blue         wood  class0

***Assigning x,y***

In [73]:
x=df.drop(columns='label')
y= df['label']

***Apply Train_test_split***

In [74]:
xtrain,xtest,ytrain,ytest= train_test_split(x,y,train_size=0.8, random_state=42)

In [75]:
xtrain

  color product_type
3  Blue         wood
0  Blue         wood
2   Red         wood

***Model creation***

In [76]:
encoder=OneHotEncoder(handle_unknown='ignore', sparse_output=False)

In [77]:
xtrain_encoder= encoder.fit_transform(xtrain[['color','product_type']])
xtest_encoder= encoder.transform(xtest[['color','product_type']])

***Scenario-1***

In [78]:
new_input=[['Blue','wood']]
encoder.transform(new_input)

c:\Users\KAPIL SHARMA\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[1., 0., 1.]])

***Scenario-2***

In [79]:
new_input=[['Blue',"Plastic"]]
encoder.transform(new_input)

c:\Users\KAPIL SHARMA\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[1., 0., 0.]])