In [74]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder

In [75]:
df=pd.DataFrame({
    "Category" : ["Electronics","Clothing","Grocery","Electronics","Clothing","Furniture","Grocery","Electronics","Furniture","Clothing"],
    "Brand" : ["Samsung","Nike","Nestle","Apple","Adidas","IKEA","Amul","Sony","Godrej","Puma"],
    "target": ["class0","class1","class2","class3","class2","class1","class2","class1","class2","class1"]
})
df

      Category    Brand  target
0  Electronics  Samsung  class0
1     Clothing     Nike  class1
2      Grocery   Nestle  class2
3  Electronics    Apple  class3
4     Clothing   Adidas  class2
5    Furniture     IKEA  class1
6      Grocery     Amul  class2
7  Electronics     Sony  class1
8    Furniture   Godrej  class2
9     Clothing     Puma  class1

***Assigning x and y***

In [76]:
x=df.drop(columns='target')
y=df['target']

***Train_test_split***

In [77]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,train_size=0.8, random_state=42)

In [78]:
xtrain

      Category    Brand
5    Furniture     IKEA
0  Electronics  Samsung
7  Electronics     Sony
2      Grocery   Nestle
9     Clothing     Puma
4     Clothing   Adidas
3  Electronics    Apple
6      Grocery     Amul

***Model Creation***

In [79]:
encoder=OneHotEncoder()

In [80]:
encoder.fit_transform(xtrain)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 16 stored elements and shape (8, 12)>

In [81]:
encoder.fit_transform(xtrain).toarray()

array([[0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0.]])

In [82]:
encoder.get_feature_names_out()

array(['Category_Clothing', 'Category_Electronics', 'Category_Furniture',
       'Category_Grocery', 'Brand_Adidas', 'Brand_Amul', 'Brand_Apple',
       'Brand_IKEA', 'Brand_Nestle', 'Brand_Puma', 'Brand_Samsung',
       'Brand_Sony'], dtype=object)

In [83]:
encoder = OneHotEncoder(sparse_output= False)
encoder.fit_transform(xtrain)

array([[0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0.]])

In [ ]:
# encoder.transform(xtest)     # ValueError: Found unknown categories ['Godrej', 'Nike'] in column 1 during transform



# encoder.transform(xtest['Category']) 

# '''
# ValueError: Expected a 2-dimensional container but got <class 'pandas.Series'> instead. Pass a DataFrame containing a single row (i.e. single sample) or a single column (i.e. single feature) instead.
# '''

ValueError: Found unknown categories ['Godrej', 'Nike'] in column 1 during transform

In [ ]:
new_input=pd.DataFrame({
    'Category':['Electronics'],
    'Brand' :['Samsung']
})
encoder.fit_transform(new_input)

array([[1., 1.]])

In [ ]:
encoder= OneHotEncoder(sparse_output=False,handle_unknown='ignore')
encoder.fit_transform(xtrain)

array([[0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0.]])

In [ ]:
encoder.transform(new_input)

array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]])